/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import giaodien.doitac.DoiTacKhachHang;
import giaodien.doitac.DoiTacNhaCungCap;
import giaodien.giaodich.CuaSoBanHang;
import giaodien.giaodich.JFrame_Thoigian1;
import giaodien.giaodich.JPanel_Hoadon1;
import giaodien.giaodich.JPanel_Nhaphang1;
import giaodien.giaodich.JPanel_Trahang;
import giaodien.giaodich.JPanel_Trahangnhap;
import giaodien.hanghoa.DanhMuc;
import giaodien.tongquan.TongQuan;
import java.awt.Window;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class JFrame_Chinh extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Chinh
     */
    public JFrame_Chinh() {
        jPanelDanhMuc = new DanhMuc();
        jPanelTongQuan = new TongQuan();
        jPanelHoaDon = new JPanel_Hoadon1();
        jPanelTraHang = new JPanel_Trahang();
        jPanelNhapHang = new JPanel_Nhaphang1();
        //jPanelTraHangNhap = new JPanel_Trahangnhap();
        jPanelKhachHang = new DoiTacKhachHang();
        jPanelNhaCungCap = new DoiTacNhaCungCap();
        
        initComponents();
        
        
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelTongQuan);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTongQuan = new javax.swing.JMenu();
        jMenuItemTongQuan = new javax.swing.JMenuItem();
        jMenuHangHoa = new javax.swing.JMenu();
        jMenuItemDanhMuc = new javax.swing.JMenuItem();
        jMenuItemThietLapGia = new javax.swing.JMenuItem();
        jMenuGiaoDich = new javax.swing.JMenu();
        jMenuItemHoaDon = new javax.swing.JMenuItem();
        jMenuItemTraHang = new javax.swing.JMenuItem();
        jMenuItemNhapHang = new javax.swing.JMenuItem();
        jMenuItemTraHangNhap = new javax.swing.JMenuItem();
        jMenuDoiTac = new javax.swing.JMenu();
        jMenuItemKhachHang = new javax.swing.JMenuItem();
        jMenuItemNhaCungCap = new javax.swing.JMenuItem();
        jMenuBaoCao = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 768));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 135, 51));
        jMenuBar1.setFont(new java.awt.Font("Arial Unicode MS", 0, 36)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(261, 32808));

        jMenuTongQuan.setText("Tổng quan");
        jMenuTongQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTongQuanActionPerformed(evt);
            }
        });

        jMenuItemTongQuan.setText("Tổng quan");
        jMenuTongQuan.add(jMenuItemTongQuan);

        jMenuBar1.add(jMenuTongQuan);

        jMenuHangHoa.setText("Hàng hóa");

        jMenuItemDanhMuc.setText("Danh mục");
        jMenuItemDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDanhMucActionPerformed(evt);
            }
        });
        jMenuHangHoa.add(jMenuItemDanhMuc);

        jMenuItemThietLapGia.setText("Thiết lập giá");
        jMenuItemThietLapGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThietLapGiaActionPerformed(evt);
            }
        });
        jMenuHangHoa.add(jMenuItemThietLapGia);

        jMenuBar1.add(jMenuHangHoa);

        jMenuGiaoDich.setText("Giao dịch");

        jMenuItemHoaDon.setText("Hóa đơn");
        jMenuItemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHoaDonActionPerformed(evt);
            }
        });
        jMenuGiaoDich.add(jMenuItemHoaDon);

        jMenuItemTraHang.setText("Trả hàng");
        jMenuItemTraHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraHangActionPerformed(evt);
            }
        });
        jMenuGiaoDich.add(jMenuItemTraHang);

        jMenuItemNhapHang.setText("Nhập hàng");
        jMenuItemNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNhapHangActionPerformed(evt);
            }
        });
        jMenuGiaoDich.add(jMenuItemNhapHang);

        jMenuItemTraHangNhap.setText("Trả hàng nhập");
        jMenuItemTraHangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraHangNhapActionPerformed(evt);
            }
        });
        jMenuGiaoDich.add(jMenuItemTraHangNhap);

        jMenuBar1.add(jMenuGiaoDich);

        jMenuDoiTac.setText("Đối tác");

        jMenuItemKhachHang.setText("Khách hàng");
        jMenuItemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKhachHangActionPerformed(evt);
            }
        });
        jMenuDoiTac.add(jMenuItemKhachHang);

        jMenuItemNhaCungCap.setText("Nhà cung cấp");
        jMenuItemNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNhaCungCapActionPerformed(evt);
            }
        });
        jMenuDoiTac.add(jMenuItemNhaCungCap);

        jMenuBar1.add(jMenuDoiTac);

        jMenuBaoCao.setText("Báo cáo");

        jMenuItem11.setText("Cuối ngày");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuBaoCao.add(jMenuItem11);

        jMenuItem12.setText("Bán hàng");
        jMenuBaoCao.add(jMenuItem12);

        jMenuItem10.setText("Hàng hóa");
        jMenuBaoCao.add(jMenuItem10);

        jMenuItem14.setText("Khách hàng");
        jMenuBaoCao.add(jMenuItem14);

        jMenuItem15.setText("Nhà cung cấp");
        jMenuBaoCao.add(jMenuItem15);

        jMenuItem13.setText("Nhân viên");
        jMenuBaoCao.add(jMenuItem13);

        jMenuItem16.setText("Tài chính");
        jMenuBaoCao.add(jMenuItem16);

        jMenuBar1.add(jMenuBaoCao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemThietLapGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThietLapGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemThietLapGiaActionPerformed

    private void jMenuItemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHoaDonActionPerformed
        // TODO add your handling code here:
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelHoaDon);
        jPanelContent.repaint();
        jPanelContent.revalidate();
      
    }//GEN-LAST:event_jMenuItemHoaDonActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuTongQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTongQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTongQuanActionPerformed

    private void jMenuItemDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDanhMucActionPerformed
        // TODO add your handling code here:
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelDanhMuc);
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
    }//GEN-LAST:event_jMenuItemDanhMucActionPerformed

    private void jMenuItemTraHangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraHangNhapActionPerformed
        // TODO add your handling code here:
         //xóa panel hiện tại
        //jPanelContent.removeAll();
        //jPanelContent.repaint();
        //jPanelContent.revalidate();
        
        //vẽ panel tong quan
        //jPanelContent.add(jPanelTraHangNhap);
        //jPanelContent.repaint();
        //jPanelContent.revalidate();
       
    }//GEN-LAST:event_jMenuItemTraHangNhapActionPerformed

    private void jMenuItemTraHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraHangActionPerformed
        // TODO add your handling code here:
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelTraHang);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemTraHangActionPerformed

    private void jMenuItemNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNhapHangActionPerformed
        // TODO add your handling code here:
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelNhapHang);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemNhapHangActionPerformed

    private void jMenuItemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKhachHangActionPerformed
        // TODO add your handling code here:
         //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelKhachHang);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemKhachHangActionPerformed

    private void jMenuItemNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNhaCungCapActionPerformed
        // TODO add your handling code here:
         //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //vẽ panel tong quan
        jPanelContent.add(jPanelNhaCungCap);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemNhaCungCapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Chinh().setVisible(true);
            }
        });
    }
    
    private DanhMuc jPanelDanhMuc;
    private TongQuan jPanelTongQuan;
    private JPanel_Hoadon1 jPanelHoaDon;
    private JPanel_Trahang jPanelTraHang; 
    private JPanel_Nhaphang1 jPanelNhapHang;
    //private JPanel_Trahangnhap jPanelTraHangNhap;
    private DoiTacKhachHang jPanelKhachHang;
    private DoiTacNhaCungCap jPanelNhaCungCap;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuBaoCao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDoiTac;
    private javax.swing.JMenu jMenuGiaoDich;
    private javax.swing.JMenu jMenuHangHoa;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItemDanhMuc;
    private javax.swing.JMenuItem jMenuItemHoaDon;
    private javax.swing.JMenuItem jMenuItemKhachHang;
    private javax.swing.JMenuItem jMenuItemNhaCungCap;
    private javax.swing.JMenuItem jMenuItemNhapHang;
    private javax.swing.JMenuItem jMenuItemThietLapGia;
    private javax.swing.JMenuItem jMenuItemTongQuan;
    private javax.swing.JMenuItem jMenuItemTraHang;
    private javax.swing.JMenuItem jMenuItemTraHangNhap;
    private javax.swing.JMenu jMenuTongQuan;
    private javax.swing.JPanel jPanelContent;
    // End of variables declaration//GEN-END:variables
}
